# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestResponseNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('url', models.TextField()),
                ('method', models.CharField(max_length=10)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('request_content_type', models.CharField(max_length=50, null=True)),
                ('request_body', models.TextField(blank=True)),
                ('request_headers', models.TextField(blank=True)),
                ('request_query_params', models.TextField(blank=True)),
                ('response_status_code', models.IntegerField()),
                ('response_body', models.TextField(blank=True)),
                ('response_content_type', models.CharField(blank=True, max_length=50, null=True)),
                ('response_headers', models.TextField(blank=True)),
            ],
        ),
    ]
