# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-17 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_viewer', '0003_auto_20170406_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestresponsenote',
            name='user_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
