# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_viewer', '0004_requestresponsenote_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestresponsenote',
            name='request_content_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requestresponsenote',
            name='response_content_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
