# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestresponsenote',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='requestresponsenote',
            name='response_status_code',
            field=models.IntegerField(verbose_name='Status_code'),
        ),
    ]
